version: "3"

services:
    postgres:
        image: "postgres:13"
        env_file:
            - .env
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    hcpairing:
        image: "rainrainwu/hcpairing:latest"
        env_file:
            - .env
        restart: always
        ports:
            - "8080:8080"


volumes:
    pgdata: